apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{ include "telemetry.namespace" . }}
  labels:
    {{- include "telemetry.labels" . | nindent 4 }}
    app: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
