apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: country-sim-monitor
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: country-sim

  namespaceSelector:
    any: true

  endpoints:
  - port: metrics
    path: /metrics
    interval: 1s