
apiVersion: v1
kind: Service
metadata:
  name: bahamas-metrics
  labels:
    app: country-sim
    country: bahamas

spec:
  selector:
    app: country-sim
    country: bahamas

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
