
apiVersion: v1
kind: Service
metadata:
  name: barbados-metrics
  labels:
    app: country-sim
    country: barbados

spec:
  selector:
    app: country-sim
    country: barbados

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
