
apiVersion: v1
kind: Service
metadata:
  name: belize-metrics
  labels:
    app: country-sim
    country: belize

spec:
  selector:
    app: country-sim
    country: belize

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
