
apiVersion: v1
kind: Service
metadata:
  name: costarica-metrics
  labels:
    app: country-sim
    country: costarica

spec:
  selector:
    app: country-sim
    country: costarica

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
