
apiVersion: v1
kind: Service
metadata:
  name: haiti-metrics
  labels:
    app: country-sim
    country: haiti

spec:
  selector:
    app: country-sim
    country: haiti

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
