
apiVersion: v1
kind: Service
metadata:
  name: nicaragua-metrics
  labels:
    app: country-sim
    country: nicaragua

spec:
  selector:
    app: country-sim
    country: nicaragua

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
