
apiVersion: v1
kind: Service
metadata:
  name: saintkittsandnevis-metrics
  labels:
    app: country-sim
    country: saintkittsandnevis

spec:
  selector:
    app: country-sim
    country: saintkittsandnevis

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
