
apiVersion: v1
kind: Service
metadata:
  name: saintvincentandthegrenadines-metrics
  labels:
    app: country-sim
    country: saintvincentandthegrenadines

spec:
  selector:
    app: country-sim
    country: saintvincentandthegrenadines

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
