
apiVersion: v1
kind: Service
metadata:
  name: saintlucia-metrics
  labels:
    app: country-sim
    country: saintlucia

spec:
  selector:
    app: country-sim
    country: saintlucia

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
