
apiVersion: v1
kind: Service
metadata:
  name: trinidadandtobago-metrics
  labels:
    app: country-sim
    country: trinidadandtobago

spec:
  selector:
    app: country-sim
    country: trinidadandtobago

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
