
apiVersion: v1
kind: Service
metadata:
  name: unitedstates-metrics
  labels:
    app: country-sim
    country: unitedstates

spec:
  selector:
    app: country-sim
    country: unitedstates

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
