
apiVersion: v1
kind: Service
metadata:
  name: newzealand-metrics
  labels:
    app: country-sim
    country: newzealand

spec:
  selector:
    app: country-sim
    country: newzealand

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
