
apiVersion: v1
kind: Service
metadata:
  name: palau-metrics
  labels:
    app: country-sim
    country: palau

spec:
  selector:
    app: country-sim
    country: palau

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
