
apiVersion: v1
kind: Service
metadata:
  name: solomonislands-metrics
  labels:
    app: country-sim
    country: solomonislands

spec:
  selector:
    app: country-sim
    country: solomonislands

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
