
apiVersion: v1
kind: Service
metadata:
  name: tuvalu-metrics
  labels:
    app: country-sim
    country: tuvalu

spec:
  selector:
    app: country-sim
    country: tuvalu

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
