
apiVersion: v1
kind: Service
metadata:
  name: vanuatu-metrics
  labels:
    app: country-sim
    country: vanuatu

spec:
  selector:
    app: country-sim
    country: vanuatu

  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
